Input Notebook:  /data/aglinska/BC-fMRI-AE/Notebooks/004-SFARI-compcorr-filter.ipynb
Output Notebook: /data/aglinska/BC-fMRI-AE/Assets/data_preprocessed_sfari-run1_notebooks/17-run2-sfari-compcorr.ipynb
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/Grammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmpk0wycpl8'
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/PatternGrammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmp2_nerlia'
Executing:   0%|          | 0/70 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   1%|▏         | 1/70 [00:05<06:02,  5.26s/cell]Executing:   4%|▍         | 3/70 [00:30<08:22,  7.50s/cell]Executing:   7%|▋         | 5/70 [00:30<05:42,  5.27s/cell]Executing:  10%|█         | 7/70 [00:32<04:09,  3.96s/cell]Executing:  13%|█▎        | 9/70 [00:32<02:50,  2.79s/cell]Executing:  16%|█▌        | 11/70 [00:32<01:56,  1.98s/cell]Executing:  19%|█▊        | 13/70 [00:33<01:20,  1.41s/cell]Executing:  21%|██▏       | 15/70 [00:33<00:55,  1.01s/cell]Executing:  24%|██▍       | 17/70 [00:38<01:22,  1.55s/cell]Executing:  27%|██▋       | 19/70 [00:39<00:56,  1.10s/cell]Executing:  30%|███       | 21/70 [00:39<00:39,  1.25cell/s]Executing:  33%|███▎      | 23/70 [00:39<00:27,  1.72cell/s]Executing:  36%|███▌      | 25/70 [00:39<00:19,  2.32cell/s]Executing:  39%|███▊      | 27/70 [00:39<00:13,  3.09cell/s]Executing:  41%|████▏     | 29/70 [00:40<00:13,  3.06cell/s]Executing:  43%|████▎     | 30/70 [00:40<00:11,  3.35cell/s]Executing:  46%|████▌     | 32/70 [00:40<00:08,  4.24cell/s]Executing:  47%|████▋     | 33/70 [00:45<00:57,  1.55s/cell]Executing:  47%|████▋     | 33/70 [00:48<00:54,  1.47s/cell]
Traceback (most recent call last):
  File "/data/aglinska/anaconda3/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [24]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-14dc412227e8> in <module>
      7 epi_scrubbed = data['epi'].numpy()[:,:,:,~scrub_idx]
      8 
----> 9 mat = epi_scrubbed.reshape(-1,epi_scrubbed.shape[-1]).transpose()
     10 scrubbed_nii = make_4depi(mat,data['epi'])
     11 

ValueError: cannot reshape array of size 0 into shape (0)

