Input Notebook:  /data/aglinska/BC-fMRI-AE/Notebooks/004-ABIDE-I-and-II-compcorr-filter.ipynb
Output Notebook: /data/aglinska/BC-fMRI-AE/Assets/data_preprocessed_f3_notebooks/03_preprocess_1253.ipynb
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/Grammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmpj0b6enle'
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/PatternGrammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmp4fegi2eo'
Executing:   0%|          | 0/73 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   1%|▏         | 1/73 [00:02<02:46,  2.31s/cell]Executing:   4%|▍         | 3/73 [00:10<03:21,  2.87s/cell]Executing:   7%|▋         | 5/73 [00:10<02:18,  2.03s/cell]Executing:  10%|▉         | 7/73 [00:10<01:34,  1.44s/cell]Executing:  12%|█▏        | 9/73 [00:11<01:05,  1.03s/cell]Executing:  15%|█▌        | 11/73 [00:11<00:45,  1.36cell/s]Executing:  18%|█▊        | 13/73 [00:16<01:17,  1.29s/cell]Executing:  19%|█▉        | 14/73 [00:16<00:55,  1.07cell/s]Executing:  21%|██        | 15/73 [00:16<00:40,  1.44cell/s]Executing:  22%|██▏       | 16/73 [00:16<00:30,  1.90cell/s]Executing:  23%|██▎       | 17/73 [00:16<00:22,  2.45cell/s]Executing:  25%|██▍       | 18/73 [00:16<00:18,  3.06cell/s]Executing:  26%|██▌       | 19/73 [00:17<00:14,  3.70cell/s]Executing:  27%|██▋       | 20/73 [00:17<00:11,  4.48cell/s]Executing:  29%|██▉       | 21/73 [00:17<00:10,  5.16cell/s]Executing:  32%|███▏      | 23/73 [00:17<00:08,  6.05cell/s]Executing:  33%|███▎      | 24/73 [00:18<00:17,  2.73cell/s]Executing:  36%|███▌      | 26/73 [00:18<00:12,  3.63cell/s]Executing:  38%|███▊      | 28/73 [00:18<00:09,  4.72cell/s]Executing:  41%|████      | 30/73 [00:18<00:07,  5.98cell/s]Executing:  44%|████▍     | 32/73 [00:18<00:05,  7.34cell/s]Executing:  47%|████▋     | 34/73 [00:19<00:05,  7.34cell/s]Executing:  49%|████▉     | 36/73 [00:22<00:20,  1.80cell/s]Executing:  49%|████▉     | 36/73 [00:23<00:24,  1.50cell/s]
Traceback (most recent call last):
  File "/data/aglinska/anaconda3/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [23]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-23-14dc412227e8> in <module>
     10 scrubbed_nii = make_4depi(mat,data['epi'])
     11 
---> 12 rmat = regress(mat,data['conf'].iloc[~scrub_idx])
     13 
     14 rmat_nii = make_4depi(rmat,data['epi'])

<ipython-input-13-92b9476e4852> in regress(flat_epi, conf, idx)
     20 
     21 
---> 22     X = conf[keys].values[idx]
     23     n = X.shape[0]
     24     X = np.hstack((X,np.ones(n)[:,np.newaxis])) # Add mean

~/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2906             if is_iterator(key):
   2907                 key = list(key)
-> 2908             indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
   2909 
   2910         # take() does not accept boolean indexers

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in _get_listlike_indexer(self, key, axis, raise_missing)
   1252             keyarr, indexer, new_indexer = ax._reindex_non_unique(keyarr)
   1253 
-> 1254         self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
   1255         return keyarr, indexer
   1256 

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1302             if raise_missing:
   1303                 not_found = list(set(key) - set(ax))
-> 1304                 raise KeyError(f"{not_found} not in index")
   1305 
   1306             # we skip the warning on Categorical

KeyError: "['a_comp_cor_04', 'a_comp_cor_03'] not in index"

