Input Notebook:  /data/aglinska/BC-fMRI-AE/Notebooks/004-ABIDE-I-and-II-compcorr-filter.ipynb
Output Notebook: /data/aglinska/BC-fMRI-AE/Assets/data_preprocessed_f3_notebooks/03_preprocess_1896.ipynb
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/Grammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmp0j620h3l'
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/PatternGrammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmp_suts4e0'
Executing:   0%|          | 0/73 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   1%|▏         | 1/73 [00:02<02:56,  2.45s/cell]Executing:   4%|▍         | 3/73 [00:10<03:28,  2.97s/cell]Executing:   7%|▋         | 5/73 [00:10<02:22,  2.10s/cell]Executing:  10%|▉         | 7/73 [00:11<01:38,  1.49s/cell]Executing:  12%|█▏        | 9/73 [00:13<01:28,  1.38s/cell]Executing:  12%|█▏        | 9/73 [00:15<01:48,  1.69s/cell]
Traceback (most recent call last):
  File "/data/aglinska/anaconda3/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [9]":
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-9-a6d66e01105d> in <module>
----> 1 files = os.listdir(bids_dir)
      2 files = np.array(files)
      3 
      4 files.sort()
      5 files

FileNotFoundError: [Errno 2] No such file or directory: '/data/aglinska/data/ABIDE2/Derivatives/fmriprep4/sub-28712/ses-1/func/'

