Input Notebook:  /data/aglinska/BC-fMRI-AE/Notebooks/004-ABIDE-I-and-II-compcorr-filter.ipynb
Output Notebook: /data/aglinska/BC-fMRI-AE/Assets/data_preprocessed_f3_notebooks/03_preprocess_1138.ipynb
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/Grammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmpe41zgxdx'
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/PatternGrammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmpcl_a1_nt'
Executing:   0%|          | 0/73 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   1%|▏         | 1/73 [00:05<06:22,  5.31s/cell]Executing:   4%|▍         | 3/73 [00:18<06:41,  5.74s/cell]Executing:   7%|▋         | 5/73 [00:18<04:34,  4.04s/cell]Executing:  10%|▉         | 7/73 [00:19<03:07,  2.85s/cell]Executing:  12%|█▏        | 9/73 [00:19<02:09,  2.02s/cell]Executing:  15%|█▌        | 11/73 [00:19<01:28,  1.43s/cell]Executing:  18%|█▊        | 13/73 [00:24<01:45,  1.76s/cell]Executing:  21%|██        | 15/73 [00:24<01:12,  1.25s/cell]Executing:  23%|██▎       | 17/73 [00:24<00:49,  1.12cell/s]Executing:  26%|██▌       | 19/73 [00:24<00:34,  1.55cell/s]Executing:  29%|██▉       | 21/73 [00:24<00:24,  2.13cell/s]Executing:  32%|███▏      | 23/73 [00:24<00:17,  2.89cell/s]Executing:  34%|███▍      | 25/73 [00:25<00:15,  3.01cell/s]Executing:  37%|███▋      | 27/73 [00:25<00:11,  3.99cell/s]Executing:  40%|███▉      | 29/73 [00:25<00:08,  5.16cell/s]Executing:  42%|████▏     | 31/73 [00:25<00:06,  6.46cell/s]Executing:  45%|████▌     | 33/73 [00:26<00:05,  6.89cell/s]Executing:  48%|████▊     | 35/73 [00:26<00:04,  8.08cell/s]Executing:  51%|█████     | 37/73 [00:33<00:39,  1.10s/cell]Executing:  51%|█████     | 37/73 [00:34<00:33,  1.06cell/s]
Traceback (most recent call last):
  File "/data/aglinska/anaconda3/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [24]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-ed678b2a363d> in <module>
----> 1 rfmat_nii = filt(im=rmat_nii,tr=data['tr'],lowf=.01,highf=.1,order=3)
      2 srfmat_nii = ants.smooth_image(image=rfmat_nii,sigma=4,sigma_in_physical_coordinates=True,FWHM=True,max_kernel_width=32)

<ipython-input-17-24fc9497fa79> in filt(im, tr, lowf, highf, order)
      1 def filt(im,tr,lowf=.01,highf=.1,order=3):
----> 2     imfilt = ants.bandpass_filter_matrix(im,tr=tr, lowf=lowf, highf=highf, order=order)
      3     return imfilt

~/anaconda3/lib/python3.8/site-packages/ants/utils/quantile.py in bandpass_filter_matrix(matrix, tr, lowf, highf, order)
    288     matrixOut = matrix.copy()
    289     for k in range( ncolumns ):
--> 290         matrixOut[:,k] = butter_bandpass_filter(
    291             matrix[:,k], lowf, highf, fs, order=order )
    292     return matrixOut

~/anaconda3/lib/python3.8/site-packages/ants/utils/quantile.py in butter_bandpass_filter(data, lowcut, highcut, fs, order)
    280     def butter_bandpass_filter(data, lowcut, highcut, fs, order ):
    281         b, a = butter_bandpass(lowcut, highcut, fs, order=order)
--> 282         y = filtfilt(b, a, data)
    283         return y
    284 

~/anaconda3/lib/python3.8/site-packages/scipy/signal/signaltools.py in filtfilt(b, a, x, axis, padtype, padlen, method, irlen)
   3891 
   3892     # method == "pad"
-> 3893     edge, ext = _validate_pad(padtype, padlen, x, axis,
   3894                               ntaps=max(len(a), len(b)))
   3895 

~/anaconda3/lib/python3.8/site-packages/scipy/signal/signaltools.py in _validate_pad(padtype, padlen, x, axis, ntaps)
   3941     # x's 'axis' dimension must be bigger than edge.
   3942     if x.shape[axis] <= edge:
-> 3943         raise ValueError("The length of the input vector x must be greater "
   3944                          "than padlen, which is %d." % edge)
   3945 

ValueError: The length of the input vector x must be greater than padlen, which is 21.

