Input Notebook:  /data/aglinska/BC-fMRI-AE/Notebooks/016-get-split-cmats-SFARI.ipynb
Output Notebook: /data/aglinska/BC-fMRI-AE/Assets/papermill-SFARI-extract/preproc-200-run2.ipynb
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/Grammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmp3rfra_ab'
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/PatternGrammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmplrye9bcx'
Executing:   0%|          | 0/29 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   3%|▎         | 1/29 [00:01<00:29,  1.05s/cell]Executing:  10%|█         | 3/29 [00:01<00:19,  1.32cell/s]Executing:  14%|█▍        | 4/29 [00:01<00:14,  1.74cell/s]Executing:  21%|██        | 6/29 [00:13<00:51,  2.25s/cell]Executing:  31%|███       | 9/29 [00:17<00:38,  1.91s/cell]Executing:  31%|███       | 9/29 [00:18<00:40,  2.03s/cell]
Traceback (most recent call last):
  File "/data/aglinska/anaconda3/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [9]":
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-03d5b8d2d3b2> in <module>
      1 pref = prefs[0]
----> 2 sub = subjects[s]

IndexError: list index out of range

